### ISSUE TITLE
Multiple rendering of no-captcha in the same page

### ISSUE THREAD

**Issue by tranceptor** [anhskohbo/no-captcha#10]
Hello, I need to show multiple captcha on the same page (I have two different forms, a subscription and an unsubscription and they must stay on the same page), but just the first one is shown.

How can I explicitly render the second captcha? 

I use Laravel 4.2. 
Thank you very much.

**Comment by arcanedev-maroc** [comment]
Check this : https://github.com/ARCANEDEV/noCAPTCHA/blob/master/examples/multiple-captchas.php

**Comment by dvolve** [comment]
Hi Kids!
I am unable to decypher arcanedev's response into a laravel 5.1 scenario.
Have the same situation as tranceptor.
Any suggestions regarding getting a multiple form with recaptcha?
Cheers in advance :)

**Comment by arcanedev-maroc** [comment]
Can you be more specific about your issue ??

You also need to check this : https://github.com/ARCANEDEV/noCAPTCHA/issues/27

If you found an issue by using my package, please create an issue with your case.

**Comment by dvolve** [comment]
Thanks for the response.
I am going to give it a good look - will keep you posted.
Your package is awesome by the way :)
Cheers

**Comment by arcanedev-maroc** [comment]
Thanks @dvolve :+1:

**Comment by ariefwt** [comment]
Hello @anhskohbo, are you planning to fix this issue? 😄

**Comment by kualojo** [comment]
+1: Also something we were looking for.

**Comment by seltix5** [comment]
i created a pull request with some updates that will make possible multiple calls on the same page without requesting each time the api :

https://github.com/anhskohbo/no-captcha/pull/57

**Comment by anhskohbo** [comment]
Thanks @seltix5
