### ISSUE TITLE
How do i remove this package from my project?

### ISSUE THREAD

**Issue by nikklass** [anhskohbo/no-captcha#102]
I installed this package before but want to remove. I deleted the line from composer.json, removed the entries in config.app.php and did a composer update and composer dump-autoload -o. But when i run my project i still get an error: 

```
In ProviderRepository.php line 208:                                                              
  Class 'Anhskohbo\NoCaptcha\NoCaptchaServiceProvider' not found
``` 
Is there anything more I have to do?

**Comment by PixellUp** [comment]
Go to in `app/config/app.php` and remove the following line `Anhskohbo\NoCaptcha\NoCaptchaServiceProvider::class`. This should allow the composer to uninstall the package.

**Comment by nikklass** [comment]
i did exactly that but still got the same error. I have uninstalled other packages in the same manner before but couldnt figure out why i couldnt do the same with this one. Anyway i resorted to just starting up a new laravel project and copied essential files in there minus no-captcha files and settings. Project is ok now. Thanx.
