### ISSUE TITLE
How can validate it in front-end?

### ISSUE THREAD

**Issue by rajshah1609** [anhskohbo/no-captcha#106]
Is there a way to validate this in front-end? If the user doesn't click the recaptcha then it should not allow the form to be submitted.

**Comment by ceejayoz** [comment]
reCAPTCHA creates a hidden textarea element with an ID of `g-recaptcha-response` you can check the value of for validation purposes. It'll have an empty string if the user hasn't completed the captcha yet.

**Comment by rajshah1609** [comment]
Yeah was doing that. I found that solution after creating the issue. Thank you.
