### ISSUE TITLE
Mistake in the documentation

### ISSUE THREAD

**Issue by Datalink-Wouter** [anhskohbo/no-captcha#112]
Hi,

In the documentation you say "Add NOCAPTCHA_SECRET and NOCAPTCHA_SITEKEY in .env file".
Those should be CAPTCHA_SECRET and CAPTCHA_SITEKEY.

Because in the config-file you use 
  'secret' => env('CAPTCHA_SECRET', 'default_secret'),
  'sitekey' => env('CAPTCHA_SITEKEY', 'default_sitekey'), 

Kind regards

**Comment by anhskohbo** [comment]
It still is `NOCAPTCHA_SECRET` and `NOCAPTCHA_SITEKEY`

https://github.com/anhskohbo/no-captcha/blob/master/src/config/captcha.php
