### ISSUE TITLE
Captcha is not showing, div is present

### ISSUE THREAD

**Issue by danifantom** [anhskohbo/no-captcha#123]
I'm using the method NoCaptcha::display() but the captcha widget won't show. If I try to submit the form anyways, it say's Please verify that you are not a robot!.
Not sure what's going on.
![screenshot_3](https://user-images.githubusercontent.com/16234163/47684785-d80a1080-dbb2-11e8-8924-701caf3fcbf5.jpg)

![screenshot_3](https://user-images.githubusercontent.com/16234163/47874420-85b73280-ddf2-11e8-865d-17b087cf341a.jpg)

The keys are correct and the domain is allowed at the recaptcha settings

**Comment by anhskohbo** [comment]
Did you try open browser console to see?

**Comment by danifantom** [comment]
Yes. Nothing is showing

**Comment by mohabhassan** [comment]
same here, exact same symptoms

**Comment by mohabhassan** [comment]
Check if your javascript is being loaded correctly, ie `{!! NoCaptcha::renderJs() !!}`

**Comment by danifantom** [comment]
I've solved the issue. It was a problem with my keys
