### ISSUE TITLE
How to add an extra class for submit button?

### ISSUE THREAD

**Issue by Racterrus** [anhskohbo/no-captcha#129]
I use invisible recaptcha, so I create a submit button using `{!! NoCaptcha::displaySubmit('my-form-id', 'submit now!', ['data-theme' => 'dark']) !!}`
As a result i have:
`<button data-callback="onSubmitloginform" data-sitekey="xxxxxxAAIjtNYEnJiXvwvofhxxxxxxxxxl" class="g-recaptcha"><span>submit now!</span></button>`
But I have to add additional classes to make a proper style, like 
`<button data-callback="onSubmitloginform" data-sitekey="xxxxxxAAIjtNYEnJiXvwvofhxxxxxxxxxl" class="g-recaptcha class1 class2 class3 btn btn-primary"><span>submit now!</span></button>`

How can I do it?

**Comment by adrianriyadi** [comment]
just use something like this and that's gonna work:
``` {!! NoCaptcha::displaySubmit('contactForm', 'send message', ['class' => 'class1 class2 class3 btn btn-primary']) !!}```
