### ISSUE TITLE
Class 'NoCaptcha' not found

### ISSUE THREAD

**Issue by entoniperez** [anhskohbo/no-captcha#133]
It works fine on local, but I get this message on production: 
`"Class 'Anhskohbo\NoCaptcha\NoCaptchaServiceProvider' not found"`.

Any idea? My Laravel version is 5.7.

**Comment by Solomon04** [comment]
@entoniperez have you done a `composer install` on the production server?

**Comment by entoniperez** [comment]
I'm sorry, now it works fine, this issue can be deleted. I'm a newbie and it's my fault, I have shared hosting and some dependencies are missing. For who could has the same problem, delete all project from the server and re-upload all project. This should fix all dependencies. Thanks.

**Comment by hardevine** [comment]
on production we were doing 
`composer install --no-dev --no-interaction --prefer-dist`
```
Package operations: 1 install, 0 updates, 0 removals
  - Installing anhskohbo/no-captcha (3.3.0): Downloading (100%)
Generating optimized autoload files
```
changed it to

`composer install --no-dev`

```
Installing dependencies from lock file
Package operations: 12 installs, 0 updates, 0 removals
  - Installing anhskohbo/no-captcha (3.3.0): Loading from cache
  - Installing nicmart/tree (0.3.0): Loading from cache
  - Installing spatie/temporary-directory (1.2.4): Loading from cache
  - Installing spatie/image-optimizer (1.2.1): Loading from cache
  - Installing league/glide (1.6.0): Loading from cache
  - Installing spatie/image (1.7.6): Loading from cache
  - Installing spatie/browsershot (3.37.2): Loading from cache
  - Installing tightenco/collect (v7.26.1): Loading from cache
  - Installing symfony/dom-crawler (v5.1.5): Loading from cache
  - Installing spatie/robots-txt (1.0.7): Loading from cache
  - Installing spatie/crawler (4.7.5): Loading from cache
  - Installing spatie/laravel-sitemap (5.8.0): Loading from cache
Generating optimized autoload files
```
now it works 👍

**Comment by maruf002** [comment]
i am facing same problem, it works fine locally but not in production ('class not found'),, any solution??

**Comment by entoniperez** [comment]
> i am facing same problem, it works fine locally but not in production ('class not found'),, any solution??

You might need to ppload your local `/vendor` directory
