### ISSUE TITLE
Readme.md outdated?

### ISSUE THREAD

**Issue by lloricode** [anhskohbo/no-captcha#136]
There no available facades, while in read me it has

**Comment by anhskohbo** [comment]
It's that? https://github.com/anhskohbo/no-captcha/blob/master/src/Facades/NoCaptcha.php

**Comment by lloricode** [comment]
@anhskohbo, sorry i mean `alias` for that

**Comment by lloricode** [comment]
https://github.com/anhskohbo/no-captcha/blob/3.0.4/composer.json#L31

i use that but give error

**Comment by lloricode** [comment]
wait try to figure out if is mine has problem, thank by the way @anhskohbo
