### ISSUE TITLE
not working laravel 5.8

### ISSUE THREAD

**Issue by salamat1307** [anhskohbo/no-captcha#138]
I am using Laravel 5.8, no captcha 3.0.4 and google recaptcha v3, but not working

**Comment by anhskohbo** [comment]
this package support recaptcha v2 only

**Comment by salamat1307** [comment]
@anhskohbo thanks for quick reply, I changed to recaptcha v2, but also not working

**Comment by salamat1307** [comment]
@anhskohbo I think the version of laravel and the version of your package do not support each other

**Comment by salamat1307** [comment]
Please update it for laravel 5.8* version

**Comment by henriquepalazzo** [comment]
So, it's not working with 5.8?

**Comment by JaceyBennett** [comment]
I have Laravel 5.8.29. I installed your package with Composer:

```
$ composer require anhskohbo/no-captcha
Using version ^3.0 for anhskohbo/no-captcha
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing anhskohbo/no-captcha (3.0.4): Downloading (100%)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: anhskohbo/no-captcha
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: srmklive/paypal
Package manifest generated successfully.
```

When I put  `{!! NoCaptcha::display() !!}`

 in my view, nothing happens. The reCaptcha does not show.

**Comment by MarlonRaphael** [comment]
Estou com a versão 5.8.29 do Laravel e aparece pra mim, porém, com uma mensagem de erro:

**ERRO para o proprietário do site: o tipo de chave é inválido**

**Comment by hanijazzar** [comment]
you need to add `<script src="//www.google.com/recaptcha/api.js"></script>` to your page. It's strange that nobody mentions this in the documentation

**Comment by dodedodo33** [comment]
Please check the usage section : https://github.com/anhskohbo/no-captcha#usage

You need to include the script in your blade template before calling display using:
```
{!! NoCaptcha::renderJs() !!}
```

This snippet can be placed in the html <head> section as well, since the script is loaded with async and defer attributes it won't block rendering.

This package does support Laravel 5.8, but does not support ReCaptcha V3. The V3 works quite differently from the V2 ReCaptha's.

**Comment by FahadHussain2020** [comment]
i am verifying the reCaptcha challenge but still i am getting the captcha field is required 
can anybody help me out !!
