### ISSUE TITLE
Laravel 6.0 Support

### ISSUE THREAD

**Issue by swiftdesignstudio** [anhskohbo/no-captcha#146]
Could you please add support for Laravel 6.0 

illuminate/support v6.*

**Comment by alvinbakker** [comment]
Yeah, please

**Comment by dodedodo33** [comment]
The master branch already includes 6.0 support. You can use "dev-master" until a new release is drafted :)

**Comment by alvinbakker** [comment]
Confirmed!

**Comment by alvinbakker** [comment]
Greets, Alvin
