### ISSUE TITLE
Laravel 6 support?

### ISSUE THREAD

**Issue by Luppakorva** [anhskohbo/no-captcha#154]
Should this package work with Laravel 6 and above?

When I try to add the captcha into view I get: 

Argument 1 passed to GuzzleHttp\Client::__construct() must be of the type array, null given, called in ...mypath/vendor/anhskohbo/no-captcha/src/NoCaptcha.php on line 50

**Comment by Luppakorva** [comment]
Figured it out. Anyone encountering this possibly in the future, I didn't clear my .env cache and didn't have the nocaptcha key and values set up leading to this error. Clearing the config cache naturally fixed the problem.

**Comment by siddharth018** [comment]
ddd
