### ISSUE TITLE
ERROR for site owner: Invalid site key

### ISSUE THREAD

**Issue by chuksdsilent** [anhskohbo/no-captcha#161]
I am getting this error.

**Comment by ashiralibutt** [comment]
> I am getting this error.

i'm alos getting same error please guide me about it

**Comment by khairulhasanmd** [comment]
Use v3 site keys
Also please keep in mind that the secret and site keys are put in example as following order, I was also made mistake by filling secret to site key and site key to secret.
NOCAPTCHA_SECRET=
NOCAPTCHA_SITEKEY=

**Comment by rdgutierrez** [comment]
> Use v2 site keys.
> Add also local domain(set up virtualhost locally) in google settings page if you need to test locally.
> Also please keep in mind that the secret and site keys are put in example as following order, I was also made mistake by filling secret to site key and site key to secret.
> NOCAPTCHA_SECRET=
> NOCAPTCHA_SITEKEY=

I did the same mistake, two hours wasted, until i read your comment
