### ISSUE TITLE
Guzzle Support for 7.x

### ISSUE THREAD

**Issue by schonhoff** [anhskohbo/no-captcha#162]
Hello,

is there a possibility that this package is supporting the new guzzle 7.x version? It shouldn't break anything.

**Comment by anhskohbo** [comment]
Let me try with guzzle 7

**Comment by andrewwindfall** [comment]
Any luck with this?

**Comment by anhskohbo** [comment]
Thank you everyone, guzzle 7 is supported in the next release!
