### ISSUE TITLE
not working with Laravel 8*

### ISSUE THREAD

**Issue by wowzone** [anhskohbo/no-captcha#168]
After a fresh install or an upgrade to Laravel 8 from 7.2.* shows an error of dependency in illuminate/support which it requires to be downgraded or removed.

**Comment by felloz** [comment]
Any date for an update for Laravel 8?

**Comment by anhskohbo** [comment]
Now it should work. Pls upgrade to `^3.3`.

**Comment by wowzone** [comment]
> Now it should work. Pls upgrade to `^3.3`.

Thank you for your great job anhskohbo!
