### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by ikanc** [anhskohbo/no-captcha#19]
Hi,

Although I see that it's supported in the code, I did not find any mentioning for localization in your readme.
Suggest adding it.

Thanks

**Comment by subdesign** [comment]
What I did is added a single piece of code to the CLIENT_API url for quick hack, as ?hl=de where de is the language short code, in the __NoCaptcha.php__: 
```
const CLIENT_API = 'https://www.google.com/recaptcha/api.js?hl=de';
```

**Comment by ikanc** [comment]
Thanks for the input.
@anhskohbo - you might want to add this capability.

**Comment by anhskohbo** [comment]
Just do this:
```
{!! app('captcha')->display('en'); !!}
```

**Comment by emadrashdanroya** [comment]
> Illegal string offset 'data-sitekey'

**Comment by swypse** [comment]
Just make:
```
{!! app('captcha')->display([], 'en') !!}
```
