### ISSUE TITLE
validation not working

### ISSUE THREAD

**Issue by DeeJaVu** [anhskohbo/no-captcha#26]
my no-captcha validation is not working, i can signin without clicking on captcha

this is my validation code

    public function validator(array $data) {
		return Validator::make($data, [
			'username' => 'required|max:255|unique:users',
			'email' => 'required|max:255|unique:users',
			'g-recaptcha-response' => 'required|captcha',
			'password' => 'required|confirmed|min:6',
		]);
	}

username, email, password are working, what am i doing wrong ?

**Comment by yassinelazaar** [comment]
Hi,
I'm gonna go ahead and assume you are using Laravel 5.1. I've had the same issue and this is how i managed to solved:
The package is registering to the service container under the 'captcha' key. You need to change that.
In the 'NoCaptchaServiceProvider' class, your 'register' method should look like this:
```php
public function register()
    {
        $this->app->bind('recaptcha', function ($app) {
            return new NoCaptcha(
                $app['config']['captcha.secret'],
                $app['config']['captcha.sitekey']
            );
        });
    }
```
I've changed 'captcha' to 'recaptcha'.
Your 'bind' method:
```php
public function boot()
    {   
        $app = $this->app;

        $this->bootConfig();

        $app['validator']->extend('recaptcha', function ($attribute, $value) use ($app){
            return $app['recaptcha']->verifyResponse($value, $app['request']->getClientIp());
        });

        if ($app->bound('form')) {
            $app['form']->macro('recaptcha', function ($attributes = []) use ($app) {
                return $app['recaptcha']->display($attributes, $app->getLocale());
            });
        }
    }
```
The 'provides' method:
```php
public function provides()
    {
        return ['recaptcha'];
    }
```
The rule attribute is changed:
```php
'g-recaptcha-response'  => 'required|recaptcha'
```
If you are adding a custom message, don't forget to change that too.
```php
'recaptcha'  => 'Captcha verification failed, please try again.'
```

**Comment by DeeJaVu** [comment]
sorry im closing this, the code above is for my signup page, so the captcha actualy works, i forgot to implements the captcha for my login page.. My Bad
