### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by simpledev** [anhskohbo/no-captcha#30]
Hi,

The captcha work but why is there this error in the console ? 
Uncaught Error: ReCAPTCHA placeholder element must be empty

Thank's !

**Comment by NickBWM** [comment]
I'm getting the same error, but can't work out why as the placeholder element *is* empty.
This isn't the only reCaptcha script I've tried with the same error, so I'm wondering if it's an issue with reCaptcha as a service, instead of an error with this script. Is anyone else getting this error?
And is anyone able to debug/resolve this?

**Comment by paulocastellano** [comment]
+1

**Comment by NickBWM** [comment]
I worked out the issue with my site - the reCapcha code was included twice, once in the main template, and once by the script. One of the downfalls of having multiple developers on one build I guess.
I hope this helps some of you guys, as far as I've found, there is no issue with the script itself - only issues with the implementation.
Cheers,

**Comment by Anonim-khb** [comment]
Error: ReCAPTCHA placeholder element must be empty

...t does not exist");if(!Ya(fe(c)))throw Error("ReCAPTCHA placeholder element must...

**Comment by tamaghna91** [comment]
Please note the recaptcha code must not be enclosed with any kind of wrapper like div/span etc. else it will start throwing error.

**Comment by ooocrniooo** [comment]
i have the same error, and i can't resolve it!
Any other suggestions?

**Comment by simpledev** [comment]
Like this `<div>{!! app('captcha')->display(); !!}</div>` there is an error in the console but without <div> or any tag  `{!! app('captcha')->display(); !!}` it works for me.

**Comment by dima-loburec** [comment]
Just youse this for each captcha at the page if you need dynamic including:

        <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit"
                async defer>
        </script>

        <div class="g-recaptcha"></div>

        <script>
            var onloadCallback = function() {
                //remove old
                $('.g-recaptcha').html('');

                $('.g-recaptcha').each(function (i, captcha) {
                    grecaptcha.render(captcha, {
                        'sitekey' : 'your key'
                    });
                });
            };
        </script>

But it is slow. You can also define all recaptchas at page initially:
https://developers.google.com/recaptcha/docs/display
