### ISSUE TITLE
Error for site owner: Invalid set key

### ISSUE THREAD

**Issue by rinaldy31** [anhskohbo/no-captcha#33]
i am having problem with the set key, i am still confused how to figure that out.
so can u guys help me?

**Comment by Maras0830** [comment]
need to set google site key and secret key. If you don't have site key and secret key then you can create from here. First click on this link : [Recaptcha Admin](https://www.google.com/recaptcha/admin#list)

**Comment by martsie** [comment]
Make sure you are using a v2 key.
