### ISSUE TITLE
Method [validateCaptcha] does not exist.

### ISSUE THREAD

**Issue by LordAioria** [anhskohbo/no-captcha#34]
ERROR :  500 Internal Server Error
	              <h1>Whoops, looks like something went wrong.</h1>
                                        <h2 class="block_exception clear_fix">
                            <span class="exception_counter">1/1</span>
                            <span class="exception_title"><abbr title="BadMethodCallException">BadMethodCallException
</abbr> in <a title="\vendor\laravel\framework\src\Illuminate
\Validation\Validator.php line 2950" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this
.title=f;">Validator.php line 2950</a>:</span>
                            <span class="exception_message">Method [validateCaptcha] does not exist.
</span>

See all files here :  http://kopy.io/fS0H2

If i delete captcha from the validator .. it works perfectly.  
I have delete all vendor folder and redo an install and it doesn't work.

**Comment by nashsaint** [comment]
I am having the same result.  Using ajax to post form and get this error.

**Comment by anhskohbo** [comment]
See: https://github.com/anhskohbo/no-captcha/issues/46
