### ISSUE TITLE
Call to a member function display() on a non-object

### ISSUE THREAD

**Issue by shahkeyurc** [anhskohbo/no-captcha#37]
Hello,
I have added plugin, and while rendering the captcha it is giving me following error: 

Call to a member function display() on a non-object

I am using Laravel teeplus theme plugin for displaying front end of my webapplication.

**Comment by anhskohbo** [comment]
try `dd(app('captcha'))` to see what you get?

**Comment by andrewzan** [comment]
I tried running it  

> dd(app('captcha')) 

  (in blade template) and it fails

**Comment by anhskohbo** [comment]
Maybe you missing `Anhskohbo\NoCaptcha\NoCaptchaServiceProvider::class,` in providers. Pls read install doc: https://github.com/anhskohbo/no-captcha#laravel-5
