### ISSUE TITLE
Validator called twice.

### ISSUE THREAD

**Issue by ajarti** [anhskohbo/no-captcha#38]
Hi guys,
            For some reason the validation is called twice for me:

```
[2016-06-20 14:21:22] local.INFO: array (
  'success' => true,
  'challenge_ts' => '2016-06-20T14:20:50Z',
  'hostname' => 'lodgestaff.dev',
)  
[2016-06-20 14:21:23] local.INFO: array (
  'success' => false,
  'challenge_ts' => '2016-06-20T14:20:50Z',
  'hostname' => 'lodgestaff.dev',
)  
```

As you can see by the call logs, the first is fine but the second will obviously fail as it's already been called, I can't see why this is happening.

I see it's loaded 2 times in the bootstrap cache under providers & eager, could this be causing it?

Any help welcome, thanks in advance.

**Comment by jmp909** [comment]
ajarti, you are probably calling ->passes() or fails() more than once.. see here
https://github.com/anhskohbo/no-captcha/issues/45#issuecomment-243535445
