### ISSUE TITLE
captcha option help

### ISSUE THREAD

**Issue by IchamIT** [anhskohbo/no-captcha#41]
thank u sir 

i'm using laravel and i dont know  exactly how to change the theme of captcha ?

**Comment by anhskohbo** [comment]
Hi, so sorry for reply late. You can use follow code:

```
{!! app('captcha')->display(['data-theme' => 'dark']); !!}
```

As first param of `display` method, you can pass any data-attr recaptcha support:

See: https://developers.google.com/recaptcha/docs/display#render_param
