### ISSUE TITLE
->passes() and ->fails() both return true simultaneously

### ISSUE THREAD

**Issue by jmp909** [anhskohbo/no-captcha#45]
``` php
$captchaValidator = \Validator::make(Input::all(), ['g-recaptcha-response' => 'required|captcha']);
echo("passes:" .$captchaValidator->passes(). ", fails:".$captchaValidator->fails());
```

both return 1.

I can just check `->passes()` to get around it, but `->fails()` should not return 1?

maybe related to:
https://github.com/anhskohbo/no-captcha/issues/38

thanks
j

**Comment by jmp909** [comment]
calling ->passes() twice gives false on second result
```php
echo($captchaValidator->passes()); // true
echo($captchaValidator->passes()); // false  (->fails() would be true here therefore)
```

**Comment by anhskohbo** [comment]
Humm, maybe by fault of laravel validator. I try test with `required` rule and add `var_dump(1)`  in `Illuminate\Validation\Validator::validateRequired` and get same error.

I will try to ask the laravel/framework see why!

Thanks for report!

**Comment by dharmavir** [comment]
It's not Laravel validator. I ran tests outside Laravel and found that when you validate same response ('g-recaptcha-response') after initial success, all other attempts will return success false.

`$VERIFY_URL = 'https://www.google.com/recaptcha/api/siteverify';
$peer_key = version_compare(PHP_VERSION, '5.6.0', '<') ? 'CN_name' : 'peer_name';
$query['secret'] = '6LeOSAkUAAAAAGGY1MQFka7Xnnj7WbekrWIGgHmT';
$query['response'] = $_POST['g-recaptcha-response'];

$context = stream_context_create(array(
	'http' => array(
		'header' => "Content-type: application/x-www-form-urlencoded\r\n",
		'method' => 'POST',
		'content' => http_build_query($query, '', '&'),
		'verify_peer' => true,
		$peer_key => 'www.google.com',
	),
));
$response = file_get_contents($VERIFY_URL, false, $context);
print_r(json_decode($response, true));	
/* Array
(
    [success] => 1
    [challenge_ts] => 2016-10-14T19:13:07Z
    [hostname] => localsecure.cy-motion.com
) */

$response = file_get_contents($VERIFY_URL, false, $context);
print_r(json_decode($response, true));
/* Array
(
    [success] => 
    [challenge_ts] => 2016-10-14T19:13:07Z
    [hostname] => localsecure.cy-motion.com
) */

$response = file_get_contents($VERIFY_URL, false, $context);
print_r(json_decode($response, true)); // sucess = 
/* Array
(
    [success] => 
    [challenge_ts] => 2016-10-14T19:13:07Z
    [hostname] => localsecure.cy-motion.com
) */`
