### ISSUE TITLE
400 response from google.

### ISSUE THREAD

**Issue by raysn0w** [anhskohbo/no-captcha#56]
Hi,

Today without making any changes to the site I'm getting this response on the network console whenever I try to click the captcha:

```
<HTML>
<HEAD>
<TITLE>Bad Request</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Bad Request</H1>
<H2>Error 400</H2>
</BODY>
</HTML>
```

it's coming from recaptcha__es.js:236 if that helps.

Any ideas?

**Comment by asadabbas88** [comment]
I am also getting 400 error with following trace:


cl @ recaptcha__en.js:232
Dn @ recaptcha__en.js:282
f.Mj @ recaptcha__en.js:283
(anonymous) @ recaptcha__en.js:190
ih @ recaptcha__en.js:101
eh @ recaptcha__en.js:102
(anonymous) @ recaptcha__en.js:100

and circle keeps on revolving .. can some one help on this?

**Comment by raysn0w** [comment]
I think this project may be dead.

**Comment by asadabbas88** [comment]
@raysn0w  So u found any workaround?

**Comment by raysn0w** [comment]
@asadabbas88 No sir!, I just disabled the package, still looking for something else.

**Comment by DA40** [comment]
I've tried using https://github.com/ARCANEDEV/noCAPTCHA instead, but it fails the same way.  Maybe google have broken it by changing their JavaScript?

**Comment by asadabbas88** [comment]
I found the issue .. In my case I was surrounding secret and site key with square brackets .. Once removed the square brackets it worked for me

**Comment by raysn0w** [comment]
@asadabbas88 Yep! worked here also, I wonder what changed, it was working before without issues.

Thanks!
