### ISSUE TITLE
Captcha always loading

### ISSUE THREAD

**Issue by vtellez** [anhskohbo/no-captcha#59]
Hello,

I am trying to implement this component in a personal project and after registering the web and obtaining the necessary keys, I find that the check of the captcha is always loading, without getting to validate in any moment.

Checking the console, I see that a call is made to: https://www.google.com/recaptcha/api2/frame?c=03AHJ_VuvZkVycxFmRG8PCga-_lVZ58hvpdHIpuXvMsinPwIJdoi0jE46mOBsDgm75RLzHzy07XwqSGQYrTb0Pxz5eHTfSKKmkpgUkXC-K0XqLovx26mpOZt-YRo00Xy6e-MnXM5hgv2_Yxw6rVCK4yMDZUS0qwhJfjpaC-daXsKGcDGAIkmWBANQwT4_afIyE-L_-SAZb5Gmx3QNfN0eKHAj88zYW4pqDR9AchFh0yxPysI-99csl9Q3D-00odEpDoOMMf5n4YF0NV5RbCXJPytOziX2CCJrnaY44aXIfaFsyxEAYo-zuLICBXMwROBCWY12tcapsA7I9-vQ0a5k8qTuNF8pzkLHh4OYNO2C7wLCHHksoZ1iEDN_g9mJBGeCs3MgTtQuSynW9kQlcESNYaVd9aUfG0HJn0cAj1WA_Kfg5ufcGJqqTG-U&hl=es&k=202293528&v=r20170104143828&bcr=%5B142895055%2C-2063507639%2C-1165554226%2C1140559581%2C687297530%2C-318737017%2C-1458465509%5D&chr=%5B25%2C49%2C61%5D&hr=-1622409639&bg=!EhSgFDVHRmAdKci-nBpBdCK_-fys6iIHAAAAa1cAAAB7nARfG7CgVjL4pdR9_StId7_HpbSCHke5w7dds1yok6_13pI29KKAa17E9UXJljeYeEoNmCvbPHLBQMlsrbBS3fgww99jM-tAOFUoBffpK-Yu2czW1AJ66BhdkanNsPQa3Q4-AtUJD5CLdFWdMxwYFnzogvQHjHmh__dWcRduJWlRyMWDxh6I3vZLpYpBJmA_QRB270XtEUoc61PpoGiZMXMn_FASB6VJ0uFQHENAQvuFTvx62SYbCFVwTzwpOrFrzfuRv-MmUP76fx4bHcZyVNLGXqn-kAkEKAHiDSu65zMjTtAJsCmTl8kjCnbfTtaeylhoyC8pQdEDJsat5cZwuvPs7IOsPhmIZbfbs_oypnOjGr2VXcMfiss6UA-GZ9d0obhD_ECafy8bHRocjHSEGA69VIR_TGBT03JrKVSN6O-qVVbcrkGgFqX3LWrFLr9InUhAs2CjsqLwBrCGWPKuHcyPEcH3CJm2gMgg7dvko9cIs0iNqKmi1WDDrb2KYTvN9XyLEKXiEch9uPHvyFkb4CKyRQyBcj3eN7zcXathnT-pQ7G2FQCf2jLKcDetdo9fLRUMV6xzdVvGbGepkEdHxcbPmIEYT6GBgcKA7WoAffq-ujzbXtOdN6mje4OiuIRYgEqWFN093p3Q8NNjkQgClxyUBdjdPI_Zy9SQd70hIU4pIwPM4WWqdunB0NnpeNSDLaomhrNeoY3Kwo6l5TpJpWZYUYlrV0jePvww_iNqaIRnvTA9nGf3V85dW76ujCmWCb4nn4UljG8VQmEmyu268nRNclX94uNcTLjR_pQSpWA1vLrCOrAfZ-9R7vXK4ApkjObc_GrOzFf0Dn5SoD7WZazOGT7mEqx2JlrI7q18EN-66XvfmrSzq-M2U4drfBo_8NPVL4D8AmkRCnzCFhtyVuSP9-9A1IJeirWGNRsdrA7bEs2brjuCAxzUy4WycHVNevnC_bV2WXcmqxxihL8tZ6p4gs9o4smIV2h9lQKH1Uq8Hkh0J7mhyZwrIiizzhzegjdFGAw86iSRhzPq40QHQnX-ArQYJoOQzyoa_kyFdATR4C80Baq_SMm79pxe-CvkJkoBHTCQ7hs3iXxSO8WoSL7kbBHS5bFNcCbTVQNVN0DERS2nI6AYeMUEAJp_SgxwGDhaWlbwZv6VHaxM0yJXeexzJFkbRex_t9VRsZ-UPIH3rFph2tyZlalby4-9rfGdk7TtJ_yj5rp1s7QRRHwAE8j5aRk8nkFlNNquNwZ_bmQWc3yYr1zkMvmI8ObmMeqKng0oOqC8g5dlQMjDWBRYAdCdG4Zh-17avtDED5OKNBxAZkwRca7cKfr-Bf0x5BMzSr2vlD9I6osxRCh9EeltmSoVop8UuyS8ddareQBm8Cux-NCQOmzh5dhYCgCbHf6QfWpWtyPVANPAjkEBafq7Ww5HmQk3k32iZ8T-kdsRE_3_GcaFeA73fu_uJrayC1RTpFpZzmUFcj1mr5SqL-7Y4VjU
 
Where Google responds:
Bad Request

Error 400

Any ideas?

Thank you very much in advance

**Comment by raysn0w** [comment]
@vtellez try removing these [] from your key in the .env file.

**Comment by vtellez** [comment]
Thank you very much! Removing these [] has correct the issue
