### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by absemetov** [anhskohbo/no-captcha#65]
POST https://www.google.com/recaptcha/api2/reload?k=%5B6LcHTB4TAAAAAL-URIlP_8frJuWxM3GhpQZLFa8F%5D 500 ()

**Comment by insology** [comment]
Hi, how you solved this problem?

**Comment by absemetov** [comment]
I delete square brackets
https://github.com/anhskohbo/no-captcha/pull/66
