### ISSUE TITLE
Not working with https?

### ISSUE THREAD

**Issue by subdesign** [anhskohbo/no-captcha#67]
On localhost the package works very well, but the same code on a https site *always* says captcha has error. Keys are double checked! 
Any idea ?

**Comment by dann95** [comment]
can u give any log of errors?

**Comment by subdesign** [comment]
Not really. Please check the following:
- visit: https://laravel.hu
- open menu
- on right side, click to "slack" link
- enter data, press the green button

it was working well, before I added the ssl cert. this is why I think it's about ssl. 
what I read on forums, I should regenerate the keys, and use them. 
sadly I can't try it coz I left my laptop charger at company, (I'm on diff computer) so only on next monday...

**Comment by alvinbakker** [comment]
@subdesign Did it work?

**Comment by subdesign** [comment]
No sorry, I replaced with a conventional captcha for a quick solution...
