### ISSUE TITLE
cURL error 28: Operation timed out after 2001 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by joerjoers** [anhskohbo/no-captcha#87]
When the recaptcha takes too long to be validated, I am encountering the error 
`cURL error 28: Operation timed out after 2000 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

Is there any way to prevent or catch the error?

**Comment by capripio** [comment]
hmm yes, the same issue occurred!

**Comment by meyer59** [comment]
Any way to add the Guzzle timeout in the config file ?

**Comment by ja-heller** [comment]
Same here, this hasn't occurred in the old versions!

**Comment by ja-heller** [comment]
**Workaround**

Increasing the timeout in this file:

> /vendor/anhskohbo/no-captcha/src/NoCaptcha.php

`        $this->http = new Client([ 'timeout' => 7.0 ]);`

solved the problem for me.

**Comment by amirgee007** [comment]
ja-heller mate its ok its solved the issue but every time whenever i update my composer then it will reset again...

what should i do for this??

**Comment by leocarmo** [comment]
Use this to publish config file:

`
php artisan vendor:publish --provider="Anhskohbo\NoCaptcha\NoCaptchaServiceProvider"
`

then edit timeout

**Comment by anhskohbo** [comment]
I increment timeout to 30 seconds to avoid this issue.
https://github.com/anhskohbo/no-captcha/blob/master/src/config/captcha.php
