### ISSUE TITLE
Captcha not working after last update

### ISSUE THREAD

**Issue by dinajpuri** [anhskohbo/no-captcha#88]
Hello,
Captcha has been working for me. But when I updated few mins ago. captcha is gone.

Only this line in source code
`<div class="g-recaptcha" data-sitekey="xxxxx"></div>`

Btw, I'm using it with Laravel 5.5

Regards

**Comment by anhskohbo** [comment]
Seem you require `dev-master` in composer.json. Please change to stable version `^2.4`

**Comment by dinajpuri** [comment]
thank you
