### ISSUE TITLE
Composer error trying to "publish:config" in L5

### ISSUE THREAD

**Issue by Lloople** [anhskohbo/no-captcha#9]
Hi, i'm trying to install the package in my Laravel 5 app. I added the line to composer.json, made a composer update, added the service provider and I get this error when I try to run the php artisan publish:config command:

```
C:\Users\David\www\project>php artisan publish:config anhskohbo/no-captcha
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Config\Repository::package()' in C:\Users\David\www\project\vendor\anhskohbo\no-captcha\src\NoCaptchaServiceProvider.php:23
Stack trace:
#0 C:\Users\David\www\project\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(115): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}
```
Don't know if I'm doing something bad.

I also tried with commands like composer self-update and composer clear-compiled and nothing.

**Comment by MartijnThomas** [comment]
@anhskohbo might be an idea to remove the line to use 'publish:config' in L5 from the docs ;)
