### ISSUE TITLE
Call to undefined method Anhskohbo\NoCaptcha\NoCaptcha::renderJs()

### ISSUE THREAD

**Issue by IceBlueFire** [anhskohbo/no-captcha#93]
I'm using Laravel 5.5, followed all the steps (including skipping the setup steps) and keep getting the following error.

```
ErrorException (E_ERROR)
Call to undefined method Anhskohbo\NoCaptcha\NoCaptcha::renderJs() (View: /resources/views/auth/register.blade.php)
```
I simply added the ```{!! NoCaptcha::renderJs() !!}``` at the top of the blade, and included the ```{!! NoCaptcha::display() !!}``` line at the relevant position in the blade.

I see all the files listed in the vendor folder, even tried including the service and aliases lines but to no avail.

Attempted the ```php artisan config:clear``` and for fun ```composer dump-autoload``` and ```composer update``` to make sure i had all the newest packages.

Any assistance would be greatly appreciated, thanks!

**Comment by anhskohbo** [comment]
Follow this guide: https://github.com/anhskohbo/no-captcha/tree/2.4.0

README in master branch is of new feature.

**Comment by IceBlueFire** [comment]
Thanks!
